env:
  es6: true
  node: true
extends:
  - eslint:recommended
  - standard
parserOptions:
  ecmaVersion: 2018
  # Node.js 10+ almost supports features up to ES2018
  # see https://node.green/#ES2018
rules:
  no-console: off
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - "*"
        - .*
        - test/**
  prettier/prettier: error
overrides:
  - files: "*.js"
    extends:
      - plugin:prettier/recommended
  - files: "*.ts"
    extends:
      - plugin:@typescript-eslint/recommended-requiring-type-checking
      - plugin:@typescript-eslint/strict
      - plugin:import/typescript
      - plugin:prettier/recommended
    parser: "@typescript-eslint/parser"
    parserOptions:
      sourceType: module
      project:
        - ./tsconfig.json
        - ./test/tsconfig.json
    plugins:
      - "@typescript-eslint"
      - simple-import-sort
    rules:
      no-dupe-class-members: off
      # The no-unused-expressions rule does not support optional chaining operator (`?.`)
      no-unused-expressions: off
      n/no-unsupported-features/es-syntax:
        - error
        - ignores:
            - modules
      "@typescript-eslint/array-type": warn
      "@typescript-eslint/explicit-function-return-type":
        - warn
        - allowExpressions: true
      "@typescript-eslint/no-inferrable-types": off
      # Copy the no-unused-expressions rule's option contained in eslint-config-standard
      # see: https://github.com/standard/eslint-config-standard/blob/v14.1.1/eslintrc.json#L157
      "@typescript-eslint/no-unused-expressions":
        - error
        - allowShortCircuit: true
          allowTernary: true
          allowTaggedTemplates: true
      simple-import-sort/imports: error
  - files: "*.d.ts"
    rules:
      no-redeclare: off
      no-useless-constructor: off
