# https://taskfile.dev

version: "3"

tasks:
  build:
    cmds:
      - tsc
  build-readme:
    cmds:
      - readme-generator --template ./.template/readme.njk {{.CLI_ARGS}}

  clean:
    cmds:
      - del-cli ./dist/ ./test/.temp/

  fmt:
    deps:
      - |
        {{- if or
          (empty (splitArgs .CLI_ARGS))
          (has "pkg" (splitArgs .CLI_ARGS))
        -}}
          _fmt-pkg
        {{- end -}}
      - |
        {{- if or
          (empty (splitArgs .CLI_ARGS))
          (and
            (has "ts" (splitArgs .CLI_ARGS))
            (has "js" (splitArgs .CLI_ARGS))
          )
        -}}
          _fmt-xs
        {{- end -}}
      - |
        {{- if and
          (has "js" (splitArgs .CLI_ARGS))
          (not (has "ts" (splitArgs .CLI_ARGS)))
        -}}
          _fmt-js
        {{- end -}}
      - |
        {{- if and
          (has "ts" (splitArgs .CLI_ARGS))
          (not (has "js" (splitArgs .CLI_ARGS)))
        -}}
          _fmt-ts
        {{- end -}}
  _fmt-pkg:
    internal: true
    cmds:
      - prettier-package-json --write ./package.json
      - sort-package-json ./package.json
  _fmt-xs:
    internal: true
    cmds:
      - eslint --fix ./
  _fmt-js:
    internal: true
    cmds:
      - eslint --ext .js,.cjs,.mjs --fix ./
  _fmt-ts:
    internal: true
    cmds:
      - eslint --ext .ts --fix ./

  lint:
    deps: [eslint, tsc-src, tsc-test]
  eslint:
    cmds:
      - eslint ./
  tsc-src:
    cmds:
      - tsc --noEmit
  tsc-test:
    cmds:
      - tsc -p ./test/ --noEmit

  test:
    cmds:
      # Use conditional expressions to decide whether or not to run tasks
      # see https://github.com/go-task/task/issues/608#issue-1052678862
      - task: |
          {{- if not (has "--test-only" (splitArgs .CLI_ARGS)) -}}
            _test-other
          {{- end -}}
      - cmd: |
          {{- if not (has "--pre-test-only" (splitArgs .CLI_ARGS)) -}}
            vitest {{- if .DISABLE_WATCH_MODE }} run {{- end -}}
          {{- end -}}
    interactive: true
  _test-other:
    internal: true
    cmds:
      - task: test-readme
      - task: lint
  test-readme:
    cmds:
      - task: build-readme
        vars:
          CLI_ARGS: --test

  release:
    cmds:
      - task: release-validation
      - task: clean
      - task: build
      - node ./dist/bin.js --push --verbose
      - pnpm publish --access=public
  release-validation:
    deps:
      - _release-validation-git-branch
      - _release-validation-git-work-dir
      - _release-validation-test
  _release-validation-publishable:
    internal: true
    run: once
    cmds:
      - can-npm-publish --verbose
    env:
      COREPACK_ENABLE_STRICT: 0
  _release-validation-git-branch:
    internal: true
    cmds:
      - task: _release-validation-publishable
      - git-branch-is master
  _release-validation-git-work-dir:
    internal: true
    cmds:
      - task: _release-validation-publishable
      - is-git-status-clean
  _release-validation-test:
    internal: true
    cmds:
      - task: _release-validation-publishable
      - task: test
        vars:
          DISABLE_WATCH_MODE: true

  # do nothing
  # It is required to execute the following tasks:
  # ```yaml
  # tasks:
  #   example:
  #     deps:
  #       # This task name may be an empty string.
  #       # If the task with the empty name does not exist, Task will fail to run this task.
  #       - |
  #         {{- if ... -}} some-task {{- end -}}
  # ```
  # see https://github.com/go-task/task/issues/608#issue-1052678862
  "":
    internal: true
