#!/usr/bin/env sh

# shellcheck disable=SC1091
. "$(dirname -- "$0")/_/husky.sh"

# Note: This file should be POSIX compliant.
#       If you edit this file, use ShellCheck and checkbashisms to make sure it does not contain features such as bash or zsh.

./node_modules/.bin/lint-staged
