name: CI
on:
  push:
    branches:
      - master
    tags-ignore:
      - "**"
  pull_request:
    branches:
      - "**"
jobs:
  # If the "invalid" or "skip ci" labels are added to the Pull Request, do not run CI.
  # see https://github.com/sounisi5011/npm-packages/blob/2a5ca2de696eeb8b40a38de90580441c4c6c96e0/.github/workflows/ci.yaml#L12-L52
  if-run-ci:
    # see https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
    # see https://stackoverflow.com/a/67532120/4907315
    if: >-
      ${{
        ! (
             contains(github.event.pull_request.labels.*.name, 'invalid')
          || contains(github.event.pull_request.labels.*.name, 'skip ci')
        )
      }}
    runs-on: ubuntu-latest
    steps:
      - name: Check GitHub API rate limit
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # https://shogo82148.github.io/blog/2020/10/23/github-bot-using-actions/
        # https://stackoverflow.com/a/59352240/4907315
        # https://docs.github.com/ja/actions/learn-github-actions/workflow-commands-for-github-actions
        # https://qiita.com/ryo0301/items/de8ce43fe61ede66f80a
        # https://stedolan.github.io/jq/manual/v1.6/#keys,keys_unsorted
        # https://qiita.com/richmikan@github/items/2aee77ae13bee2c648f4
        run: |
          readonly DATE_FORMAT='+%Y/%m/%d %T %Z'

          RATE_LIMIT_JSON="$(gh api 'rate_limit')"
          echo "${RATE_LIMIT_JSON}" | jq -r '.resources | keys_unsorted[]' | while read -r type; do
            echo '::group::' "${type}"
            echo "${RATE_LIMIT_JSON}" | jq ".resources.${type}"
            echo "::notice::Reset time is $(date -ud "@$(echo "${RATE_LIMIT_JSON}" | jq -r ".resources.${type}.reset")" "${DATE_FORMAT}")"
            echo '::endgroup::'
          done

          core_remaining="$(echo "${RATE_LIMIT_JSON}" | jq -r ".resources.core.remaining")"
          if [ "${core_remaining}" == 0 ]; then
            core_reset="$(echo "${RATE_LIMIT_JSON}" | jq -r ".resources.core.reset")"
            echo "::error::Rate limit reached. Please wait until $(date -ud "@${core_reset}" "${DATE_FORMAT}")"
            exit 1
          elif [ "${core_remaining}" -lt 10 ]; then
            echo "::warning::The rate limit is approaching: core.remaining=${core_remaining}"
          fi

  detect-supported-node:
    needs: if-run-ci
    runs-on: ubuntu-latest
    outputs:
      versions-json: ${{ steps.detector.outputs.versions-json }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: detector
        uses: sounisi5011/npm-packages@actions/get-nodejs-versions-array-v0

  # lint:
  #   needs: if-run-ci
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Reconfigure git to use HTTP authentication
  #       # see https://stackoverflow.com/a/69634516
  #       # see https://github.com/actions/setup-node/issues/214#issuecomment-810829250
  #       shell: bash
  #       run: |
  #         git config --global \
  #           'url.https://${{ secrets.GITHUB_TOKEN }}@github.com/.insteadOf' \
  #           'ssh://git@github.com/'

  #     - name: Install Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 14.x
  #         cache: npm

  #     - name: Enable Corepack (Automatically setup a package manager for Node.js)
  #       run: |
  #         corepack enable
  #         corepack enable npm

  #     - name: Show node and npm version
  #       shell: bash
  #       run: |
  #         echo node "$(node --version)"
  #         echo npm "$(npm --version)"

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Run linter
  #       run: npm run test:other-than-unit-test

  unit-test:
    needs: detect-supported-node
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: ${{ fromJson(needs.detect-supported-node.outputs.versions-json) }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Reconfigure git to use HTTP authentication
        # see https://stackoverflow.com/a/69634516
        # see https://github.com/actions/setup-node/issues/214#issuecomment-810829250
        shell: bash
        run: |
          git config --global \
            'url.https://${{ secrets.GITHUB_TOKEN }}@github.com/.insteadOf' \
            'ssh://git@github.com/'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Enable Corepack (Automatically setup a package manager for Node.js)
        shell: bash
        run: |
          # Corepack v0.14 is the earliest version that can use the environment variable COREPACK_ENABLE_STRICT.
          # see https://github.com/nodejs/corepack/blob/v0.14.0/CHANGELOG.md#0140-2022-09-02
          # In addition, this version supports Node.js 14.14.0 or later.
          # see https://github.com/nodejs/corepack/pull/227
          readonly COREPACK_MIN_VERSION='0.14'

          exec_with_debug() {
            node - "$@" << 'EOS'
              // These characters cannot be wrapped in double quotes:
              // - !
              // - $
              // - \
              // - `
              const cannotInQuotChars = /!$\\`/;
              const quotedArgs = process.argv.slice(2)
                .map(arg => {
                  const wrapApos = `'${arg.replace(new RegExp(`'[^"${cannotInQuotChars.source}]*`, 'g'), `'"$&"'`)}'`.replace(/^''|''$/g, ``);
                  const wrapQuot = `"${arg.replace(/"[^']*/g, `"'$&'"`)}"`.replace(/^""|""$/g, ``);

                  return arg === `` || /[ !"$&'()*;<>?[\]\\`{|}~]/.test(arg) ? (
                    new RegExp(`[${cannotInQuotChars.source}]`).test(arg) || wrapApos.length <= wrapQuot.length
                      ? wrapApos
                      : wrapQuot
                  ) : arg
                })
                .join(' ');

              // The "[command]" prefix may cause the display to shift, so use it with the "setTimeout" function.
              setTimeout(() => {
                process.stderr.write(`[command]${quotedArgs}`);
                setTimeout(() => process.stderr.write("\n"), 1);
              }, 1);
          EOS
            "$@"
          }

          version_lte() {
            local op1 op2 i max_i

            # see https://genzouw.com/entry/2019/12/17/120057/1831/
            # see https://www.shellcheck.net/wiki/SC2206
            IFS='.' read -r -a op1 <<< "$1"
            IFS='.' read -r -a op2 <<< "$2"
            max_i="${#op1[@]}"
            if [[ "${#op2[@]}" -lt "${max_i}" ]]; then
              max_i="${#op2[@]}"
            fi

            for ((i=0; i<"${max_i}"; i++)); do
              if [[ "${op1[i]}" -lt "${op2[i]}" ]]; then
                return 0
              elif [[ "${op2[i]}" -lt "${op1[i]}" ]]; then
                return 1
              fi
            done
            return 0
          }

          # On Windows we can't use the CLI we installed just by running the "npm install --global ..." command.
          # This function allows use of the installed CLI.
          npm_install_global() {
            exec_with_debug npm install --global --force "$1"

            if [[ '${{ runner.os }}' == 'Windows' ]]; then
              # Windows installs global packages to a directory that has lower priority than the default node install so we also need to edit $PATH
              # see https://github.com/vercel/turbo/pull/1632/files#diff-b92a3120126a9ffe46d7d5ec3a8496ef1eac951db09e1972fac7c78438e36c42R69
              local -r globalPath="$(exec_with_debug npm config get prefix)"
              printf "%s\n[command]echo '%s' >> \$GITHUB_PATH\n" "${globalPath}" "${globalPath}"
              echo "${globalPath}" >> "${GITHUB_PATH}"

              local -r unixLikeGlobalPath="$(exec_with_debug cygpath --unix "${globalPath}")"
              printf "%s\n[command]PATH='%s':\$PATH\n" "${unixLikeGlobalPath}" "${unixLikeGlobalPath}"
              PATH="${unixLikeGlobalPath}:${PATH}"
            fi
          }

          # Note: On Windows, the `npm ls --global corepack` command cannot be used to detect the builtin Corepack.
          #       So, use this complex conditional expression.
          corepack_not_enabled() {
            local -r packageManager="$(< "${GITHUB_WORKSPACE}/package.json" jq --raw-output '.packageManager')"
            if [[ "${packageManager}" == 'npm@'* ]]; then
              [[ "npm@$(npm --version)" != "${packageManager%%+*}" ]]
            elif [[ "${packageManager}" == 'yarn@'* ]]; then
              [[ "yarn@$(yarn --version)" != "${packageManager%%+*}" ]]
            elif [[ "${packageManager}" == 'pnpm@'* ]]; then
              [[ "pnpm@$(pnpm --version)" != "${packageManager%%+*}" ]]
            else
              # see https://stackoverflow.com/a/23550347
              >&2 echo "Unsupported package manager specification: '${packageManager}'"
              exit 1
            fi
          }

          if type corepack >/dev/null 2>&1; then
            if version_lte "${COREPACK_MIN_VERSION}" "$(corepack --version)"; then
              echo '::group::Try enable Corepack'
            else
              echo "::group::Old Corepack is detected ( corepack@$(corepack --version 2>/dev/null || echo '[Execution failed; Unknown version]') ). Update this"
              npm_install_global "corepack@${COREPACK_MIN_VERSION}"
              echo '::endgroup::'

              exec_with_debug corepack --version
              if [[ "$(corepack --version)" != "${COREPACK_MIN_VERSION}."* ]]; then
                exit 1
              fi

              echo '::group::Enable Corepack'
            fi
            exec_with_debug corepack enable
            exec_with_debug corepack enable npm
            echo '::endgroup::'
          fi

          # If Corepack is not available, install it manually.
          # Note: Corepack is already installed on GitHub Actions.
          #       But it does not manage npm versions.
          #       To manage npm, Corepack must be installed via npm, which is builtin to the installed Node.js.
          if corepack_not_enabled; then
            echo '::warning::Failed to enable Corepack'

            echo '::group::Install Corepack manually'
            if type corepack >/dev/null 2>&1; then
              # Disable the built-in Corepack in GitHub Actions.
              # If enabled, problems will occur when the yarn command is executed.
              exec_with_debug corepack disable
            fi
            npm_install_global "corepack@${COREPACK_MIN_VERSION}"
            echo '::endgroup::'

            exec_with_debug corepack --version
            if [[ "$(corepack --version)" != "${COREPACK_MIN_VERSION}."* ]]; then
              exit 1
            fi

            echo '::group::Enable Corepack'
            exec_with_debug corepack enable
            exec_with_debug corepack enable npm
            echo '::endgroup::'
          fi

      - name: Show node and npm version
        shell: bash
        run: |
          echo node "$(node --version)"
          echo npm "$(npm --version)"

      # - name: Install dependencies
      #   run: npm ci || npm install

      # - name: Run unit test
      #   run: npm run test:unit-test

  # Successfully complete this job when all jobs have been completed.
  # Only by checking this job, it is possible to determine if CI is complete or not.
  # So we can simplify our GitHub status check configuration.
  # see https://github.com/orgs/community/discussions/26822
  # see https://github.com/sounisi5011/npm-packages/blob/2a5ca2de696eeb8b40a38de90580441c4c6c96e0/.github/workflows/ci.yaml#L482-L498
  complete:
    name: Complete CI
    # needs: [lint, unit-test]
    needs: unit-test
    if:
      ${{ always() && github.event.pull_request }}
      # This job is required only for Pull Requests.
      # It does not need to be run on other branches.
    runs-on: ubuntu-latest
    steps:
      - name: Check all job status
        # see https://docs.github.com/en/actions/learn-github-actions/contexts#needs-context
        # see https://docs.github.com/en/actions/learn-github-actions/expressions#contains
        # see https://stackoverflow.com/a/67532120/4907315
        if: >-
          ${{
               contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
            || contains(needs.*.result, 'skipped')
          }}
        run: exit 1
