name: CI
on:
  push:
    branches:
      - master
    tags-ignore:
      - "**"
  pull_request:
    branches:
      - "**"
jobs:
  # If the "invalid" or "skip ci" labels are added to the Pull Request, do not run CI.
  # see https://github.com/sounisi5011/npm-packages/blob/2a5ca2de696eeb8b40a38de90580441c4c6c96e0/.github/workflows/ci.yaml#L12-L52
  if-run-ci:
    # see https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
    # see https://stackoverflow.com/a/67532120/4907315
    if: >-
      ${{
        ! (
             contains(github.event.pull_request.labels.*.name, 'invalid')
          || contains(github.event.pull_request.labels.*.name, 'skip ci')
        )
      }}
    runs-on: ubuntu-latest
    steps:
      - name: Check GitHub API rate limit
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # https://shogo82148.github.io/blog/2020/10/23/github-bot-using-actions/
        # https://stackoverflow.com/a/59352240/4907315
        # https://docs.github.com/ja/actions/learn-github-actions/workflow-commands-for-github-actions
        # https://qiita.com/ryo0301/items/de8ce43fe61ede66f80a
        # https://stedolan.github.io/jq/manual/v1.6/#keys,keys_unsorted
        # https://qiita.com/richmikan@github/items/2aee77ae13bee2c648f4
        run: |
          readonly DATE_FORMAT='+%Y/%m/%d %T %Z'

          RATE_LIMIT_JSON="$(gh api 'rate_limit')"
          echo "${RATE_LIMIT_JSON}" | jq -r '.resources | keys_unsorted[]' | while read -r type; do
            echo '::group::' "${type}"
            echo "${RATE_LIMIT_JSON}" | jq ".resources.${type}"
            echo "::notice::Reset time is $(date -ud "@$(echo "${RATE_LIMIT_JSON}" | jq -r ".resources.${type}.reset")" "${DATE_FORMAT}")"
            echo '::endgroup::'
          done

          core_remaining="$(echo "${RATE_LIMIT_JSON}" | jq -r ".resources.core.remaining")"
          if [ "${core_remaining}" == 0 ]; then
            core_reset="$(echo "${RATE_LIMIT_JSON}" | jq -r ".resources.core.reset")"
            echo "::error::Rate limit reached. Please wait until $(date -ud "@${core_reset}" "${DATE_FORMAT}")"
            exit 1
          elif [ "${core_remaining}" -lt 10 ]; then
            echo "::warning::The rate limit is approaching: core.remaining=${core_remaining}"
          fi

  detect-supported-node:
    needs: if-run-ci
    runs-on: ubuntu-latest
    outputs:
      versions-json: ${{ steps.detector.outputs.versions-json }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: detector
        uses: sounisi5011/npm-packages@actions/get-nodejs-versions-array-v0

  lint:
    needs: if-run-ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Reconfigure git to use HTTP authentication
        # see https://stackoverflow.com/a/69634516
        # see https://github.com/actions/setup-node/issues/214#issuecomment-810829250
        shell: bash
        run: |
          git config --global \
            'url.https://${{ secrets.GITHUB_TOKEN }}@github.com/.insteadOf' \
            'ssh://git@github.com/'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Enable Corepack (Automatically setup a package manager for Node.js)
        run: |
          corepack enable
          corepack enable npm

      - name: Show node and package manager version
        shell: bash
        run: |
          echo node "$(node --version)"
          echo pnpm "$(pnpm --version)"
          echo "pnpm-store-path=$(pnpm store path --silent)" >> "${GITHUB_ENV}"

      - name: Cache pnpm
        uses: actions/cache@v3
        with:
          key: node-cache-${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          path: ${{ env.pnpm-store-path }}

      - name: Install dependencies
        run: pnpm install

      - name: Run linter
        run: pnpm run test:other-than-unit-test

  unit-test:
    needs: detect-supported-node
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: ${{ fromJson(needs.detect-supported-node.outputs.versions-json) }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Reconfigure git to use HTTP authentication
        # see https://stackoverflow.com/a/69634516
        # see https://github.com/actions/setup-node/issues/214#issuecomment-810829250
        shell: bash
        run: |
          git config --global \
            'url.https://${{ secrets.GITHUB_TOKEN }}@github.com/.insteadOf' \
            'ssh://git@github.com/'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Enable Corepack (Automatically setup a package manager for Node.js)
        shell: bash
        run: |
          exec_with_debug() {
            node - "$@" << 'EOS'
              // These characters cannot be wrapped in double quotes:
              // - !
              // - $
              // - \
              // - `
              const cannotInQuotChars = /!$\\`/;
              const quotedArgs = process.argv.slice(2)
                .map(arg => {
                  const wrapApos = `'${arg.replace(new RegExp(`'[^"${cannotInQuotChars.source}]*`, 'g'), `'"$&"'`)}'`.replace(/^''|''$/g, ``);
                  const wrapQuot = `"${arg.replace(/"[^']*/g, `"'$&'"`)}"`.replace(/^""|""$/g, ``);

                  return arg === `` || /[ !"$&'()*;<>?[\]\\`{|}~]/.test(arg) ? (
                    new RegExp(`[${cannotInQuotChars.source}]`).test(arg) || wrapApos.length <= wrapQuot.length
                      ? wrapApos
                      : wrapQuot
                  ) : arg
                })
                .join(' ');

              // The "[command]" prefix may cause the display to shift, so use it with the "setTimeout" function.
              setTimeout(() => {
                process.stderr.write(`[command]${quotedArgs}`);
                setTimeout(() => process.stderr.write("\n"), 1);
              }, 1);
          EOS
            "$@"
          }

          echo '::group::Install Corepack'
          # Corepack v0.17 supports Node.js 14.14.0 or later.
          # Corepack v0.18 or later (not yet released as of March 23, 2023) may also be supported, but this is not certain.
          exec_with_debug npm install --global --force 'corepack@0.17.x'
          if [[ '${{ runner.os }}' == 'Windows' ]]; then
            # Windows installs global packages to a directory that has lower priority than the default node install so we also need to edit $PATH
            # see https://github.com/vercel/turbo/pull/1632/files#diff-b92a3120126a9ffe46d7d5ec3a8496ef1eac951db09e1972fac7c78438e36c42R69
            echo "[command]npm config get prefix >> \$GITHUB_PATH"
            npm config get prefix >> "${GITHUB_PATH}"
          fi
          echo '::endgroup::'

          echo '::group::Enable Corepack'
          exec_with_debug corepack enable
          exec_with_debug corepack enable npm
          echo '::endgroup::'

      - name: Show node and package manager version
        shell: bash
        run: |
          echo node "$(node --version)"
          echo pnpm "$(pnpm --version)"
          echo "pnpm-store-path=$(pnpm store path --silent)" >> "${GITHUB_ENV}"

      - name: Cache pnpm
        uses: actions/cache@v3
        with:
          key: node-cache-${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          path: ${{ env.pnpm-store-path }}

      - name: Install dependencies
        run: pnpm install

      - name: Run unit test
        run: pnpm run test:unit-test

  # Successfully complete this job when all jobs have been completed.
  # Only by checking this job, it is possible to determine if CI is complete or not.
  # So we can simplify our GitHub status check configuration.
  # see https://github.com/orgs/community/discussions/26822
  # see https://github.com/sounisi5011/npm-packages/blob/2a5ca2de696eeb8b40a38de90580441c4c6c96e0/.github/workflows/ci.yaml#L482-L498
  complete:
    name: Complete CI
    needs: [lint, unit-test]
    if:
      ${{ always() && github.event.pull_request }}
      # This job is required only for Pull Requests.
      # It does not need to be run on other branches.
    runs-on: ubuntu-latest
    steps:
      - name: Check all job status
        # see https://docs.github.com/en/actions/learn-github-actions/contexts#needs-context
        # see https://docs.github.com/en/actions/learn-github-actions/expressions#contains
        # see https://stackoverflow.com/a/67532120/4907315
        if: >-
          ${{
               contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
            || contains(needs.*.result, 'skipped')
          }}
        run: exit 1
